service:
  name: pdf-one-more

plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1
  stage: ${opt:stage, 'development'}
  environment:
    ENV: ${self:provider.stage}

custom:
  apigwBinary:
    types:
      - "*/*"

functions:
  buildpdf:
    handler: buildpdf.buildpdf
    events:
      - http:
          path: buildpdf
          method: post
          integration: lambda-proxy
          cors: true

  generatepdf:
    handler: pdf.generatepdf
    events:
      - http:
          path: getmethepdf
          method: post
          cors: true

  numeng:
    handler: numeng.numeng
    events:
      - http:
          path: numeng
          method: get
          cors: true

  getbycontentid:
      handler: getbycontentid.getbycontentid
      events:
        - http:
            path: getbycontentid/{contentid}/{lang}
            method: get
            cors: true
            

